//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aritex.API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDAritex : DbContext
    {
        public BDAritex()
            : base("name=BDAritex")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int ListaEmpaque_Consulta_ventas_diario_unoee_sp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaEmpaque_Consulta_ventas_diario_unoee_sp");
        }
    }
}
